#!/bin/bash
#-------------------------------------------------------------------------VARIABLES-----------------------------------------------------------------------------
Password=""
Directory=""
Directory_2=""
File=""
#-------------------------------------------------------------------------FUNCTIONS---------------------------------------------------------------------------------------------

check_pkg () {
cmd_avab zip
}


cmd_avab () {
if ! command -v $1  &> /dev/null
then
echo -n " [+] Installing Required Packages...."
apt update -y ;apt upgrade -y
apt install $1 -y &> /dev/null
check_pkg
echo "(Done)"
clear
fi
}

cxt () {
files=$(ls -a)
for file in $files
do
if [[ $file == "."  ]]
then
continue
elif [[ $file == ".."  ]]
then
continue
else
fil=$(echo $file | cut -d "." -f 1)
if [[ $fil == "" ]]
then
fil=$(echo $file | cut -d "." -f 2)
fi
mv $file .$fil.$1
fi
done
}


#-------------------------------------------------------------------------LOGIC-----------------------------------------------------------------------------

check_pkg
cd $Directory
if [ ! -e $File ]
then
echo " [!] File Doesn't Exists!"
exit 0
fi
echo -n " [+] Decrypting File...."
unzip -P $Password $File &> /dev/null
echo "(Done)"
cd $Directory_2
echo -n " [+] Converting Data In Suitable Format...."
cxt mp4
echo "(Done)"
read -p " [+] Press Enter To Continue..."
cd $Directory
rm -rf $Directory_2


